dashevo/dapi

- .travis.yml
- lib/rpcServer/server.js
- package-lock.json
- package.json
This fixes a bug that prevents dapi from starting
> bugfix: revert to just passing insightAPI object when contructing command

- deploy.sh
This fixes the build, forgot this in last the Docker build script change.
> Add Docker context dir

- .env.example
- .travis.yml
- lib/grpcServer/handlers/core/updateStateHandlerFactory.js
- lib/test/.eslintrc
- lib/test/bootstrap.js
- lib/test/createStateTransition.js
- lib/test/fixtures/createPayloadFixture.js
- lib/test/fixtures/createStateTransitionFixture.js
- package-lock.json
- package.json
- scripts/core.js
- test/functional/grpcServer/handlers/core/getLastUserStateTransitionHashHandlerFactory.spec.js
- test/functional/grpcServer/handlers/core/updateStateHandlerFactory.js
- test/functional/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.spec.js
- test/integration/transactionsFilter/subscribeToNewTransactions.spec.js
- test/integration/transactionsFilter/testTransactionAgainstFilter.spec.js
- test/mocha.opts
Functional tests enabled
Functional test for `updateStateHandlerFactory`
Env variables for tests
Mocha bootstrap for tests
Bugfixes
> Implemented functional test for updateStateHandlerFactory

- package-lock.json
- package.json
- scripts/api.js
> fix: core gRPC service is not initialized

- lib/grpcServer/handlers/core/getTransactionHandlerFactory.js
- package-lock.json
- package.json
- test/functional/grpcServer/handlers/core/getTransactionHandlerFactory.js
Affected by the Transaction parsing bug as well.
> feat: `getTransaction` functional test

- lib/grpcServer/handlers/handleAbciResponse.js
- package-lock.json
- package.json
Remove rate limiter errors
Bump version to 0.12.0-dev.1
> feat: remove rate limiter errors

- package-lock.json
- package.json
Need to update DPP to new version
DPP updated to 0.14.0-dev.4
Unit tests
> feat: update dependencies (dpp to 0.14.0-dev.4, dashcore-lib to 0.18.11)

- package-lock.json
- package.json
Updated version.
Updated version to `0.14.0-dev.3`
None.
> chore: bump version to 0.14.0-dev.3

- .travis.yml
To deal with circular dependency changes we need an option to skip platform test suite tests
Add SKIP_TEST_SUITE env support to travis.yml
With Travis
None
> feat: add skip test suite option to travis

- .travis.yml
To have more consistent testing we need to have an opportunity to use unmerged dapi and drive code during tests running
Changed Travis script
Travis builds
None
> feat: install DAPI and Drive from branch in during Travis build

- .travis.yml
To have more consistent testing we need to have an opportunity to use SDK from a particular branch
Changed Travis script
Travis builds
None
> build: install SDK from branch in travis

- lib/grpcServer/handlers/core/broadcastTransactionHandlerFactory.js
- lib/grpcServer/handlers/core/coreHandlersFactory.js
- lib/grpcServer/handlers/core/getBlockHandlerFactory.js
- lib/grpcServer/handlers/core/getStatusHandlerFactory.js
- lib/grpcServer/handlers/core/getTransactionHandlerFactory.js
- lib/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js
- lib/grpcServer/handlers/platform/getDataContractHandlerFactory.js
- lib/grpcServer/handlers/platform/getDocumentsHandlerFactory.js
- lib/grpcServer/handlers/platform/getIdentityByFirstPublicKeyHandlerFactory.js
- lib/grpcServer/handlers/platform/getIdentityHandlerFactory.js
- lib/grpcServer/handlers/platform/getIdentityIdByFirstPublicKeyHandlerFactory.js
- lib/grpcServer/handlers/platform/platformHandlersFactory.js
- lib/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.js
- package-lock.json
- package.json
- scripts/api.js
- scripts/tx-filter-stream.js
- test/unit/grpcServer/handlers/core/broadcastTransactionHandlerFactory.js
- test/unit/grpcServer/handlers/core/getBlockHandlerFactory.js
- test/unit/grpcServer/handlers/core/getStatusHandlerFactory.js
- test/unit/grpcServer/handlers/core/getTransactionHandlerFactory.js
- test/unit/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getDataContractHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getDocumentsHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getIdentityByFirstPublicKeyHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getIdentityHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getIdentityIdByFirstPublicKeyHandlerFactory.js
- test/unit/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.spec.js
Update to DAPI gRPC 0.15 with versioning and moving TxFiterStream to Core service. 
Use v0 of Core and Platform services
Use Core service for `subscribeToTransactionsWithProofs` endpoint.
With tests
`subscribeToTransactionsWithProofs` endpoint moved to Core service
> feat!: update to DAPI gRPC 0.15

- package-lock.json
- package.json
To make a new pre-release we need to bump version
Bumped version
Unit tests
None
> chore: bump version to 0.15.0-dev.6

- .mocharc.yml
- package-lock.json
- package.json
- test/mocha.opts
Outdated mocha has dependency vulnerabilities
Mocha updated to 8.1.3
With tests
None
> chore: update mocha to 8.1.3

- package-lock.json
- package.json
- test/unit/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getDataContractHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getDocumentsHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getIdentitiesByPublicKeyHashesHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getIdentityByFirstPublicKeyHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getIdentityHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getIdentityIdsByPublicKeyHashesHandlerFactory.js
We need to update DPP to the latest version
DPP updated to 0.16-dev.2, tests fixed
Unit tests
> test: update DPP to 0.16-dev.2

- package-lock.json
- package.json
To make a new pre-release we need to bump version
Bumped version
Unit tests
None
> chore: bump version to 0.16.0-dev.2

- package-lock.json
- package.json
update dashcore-lib to 0.19.5
dashcore-lib updated to 0.19.5
Tests
No
> feat: update dashcore-lib to 0.19.5

- package-lock.json
- package.json
> chore(release): 0.17.0-dev.3 release

- lib/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.js
Fixing `count too big` being thrown in `subscribeToTransactionsWithProofsHandler` by backporting code from `v.16` branch
- No longer throwing an error
None.
> fix: `count too big` being thrown in `subscribeToTransactionsWithProofsHandler`

- package-lock.json
- package.json
> chore(release): DAPI 0.17.0-dev.5 release

- lib/externalApis/drive/DriveStateRepository.js
- lib/grpcServer/handlers/platform/getDataContractHandlerFactory.js
- lib/grpcServer/handlers/platform/getDocumentsHandlerFactory.js
- lib/grpcServer/handlers/platform/getIdentitiesByPublicKeyHashesHandlerFactory.js
- lib/grpcServer/handlers/platform/getIdentityHandlerFactory.js
- lib/grpcServer/handlers/platform/getIdentityIdsByPublicKeyHashesHandlerFactory.js
- package-lock.json
- package.json
- test/unit/externalApis/drive/DriveStateRepository.js
- test/unit/grpcServer/handlers/platform/getDataContractHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getDocumentsHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getIdentitiesByPublicKeyHashesHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getIdentityHandlerFactory.js
- test/unit/grpcServer/handlers/platform/getIdentityIdsByPublicKeyHashesHandlerFactory.js
Need to provide state tree proofs.
Added `prove` parameter to platform requests, `proof` parameter to platform responses.
Tests
No
> feat: provide state tree proofs

- package-lock.json
- package.json
To make a new pre-release we need to bump version
Bumped version
Unit tests
None
> chore: bump version to 0.17.0-dev.6

- package-lock.json
- package.json
- fixes occasional tx-filter stream crash by updating `grpc-common` dependency
Updated dependencies to the latest versions
Run the tests
None
> chore(release): DAPI 0.16.2 release

- CHANGELOG.md
- package-lock.json
- package.json
Release v0.17
- Update changelog
- Bump version
None
None
> chore(release): update changelog and bump version to 0.17.0

- package-lock.json
- package.json
> chore: bump version to 0.18.0-dev.5

- package-lock.json
- package.json
> chore: bump version to 0.18.0-dev.6

- Dockerfile
- docker/cache/.cache/.gitignore
- docker/cache/.npm/.gitignore
To speed up repeated Docker builds we should be able to provide npm and node gyp cache.
- Add npm and node-gyp cache dirs
With running docker build
None
> feat: enable Docker build npm cache

- .travis.yml
- package-lock.json
- package.json
> chore: bump version to 0.19.0-dev.1

- .github/workflows/test_and_release.yml
Minor fixes
- fix typo
- remove unnecessary input
> chore(ci): typo and unnecessary input

- .github/workflows/test_and_release.yml
`sdk-install` input was inconsistent with other steps
Rename `sdk-install` to `sdk-branch` for consistency
With CI
None
> chore(ci): rename sdk-install to sdk-branch

- .github/workflows/test_and_release.yml
AWS hosting costs are high. Enabling support for ARM arch can help reduce costs.
Enable multi-arch build
Tested in CI
None
> chore(ci): enable multi-arch Docker build

- .github/workflows/test_and_release.yml
Update CI to use action versions
- Use version tags for actions
In CI
None
> chore(ci): use action version tags

- .github/workflows/test_and_release.yml
CI was failing with `unable to find version buildkit-caching-support`
Use production version of action
in CI
> ci: use production branch for start network action

- .github/workflows/test_and_release.yml
The docker metadata action moved
Update metadata action target
in CI
None
> ci: update metadata action repo

- lib/externalApis/dashcore/rpc.js
- lib/grpcServer/handlers/core/getTransactionHandlerFactory.js
- package-lock.json
- package.json
- test/unit/grpcServer/handlers/core/getTransactionHandlerFactory.js
And additional info was added to a response along with transaction
- added `blockHash`, `confirmations`, `height`, `isInstantLocked`, and `isChainLocked` fields
Unit tests
None.
>  feat: additional info in `getTransaction` response

- .github/workflows/test_and_release.yml
Builds were failing with `Error: Process completed with exit code 2.` in case of a cache miss in the release step
- Remove the debug step
In CI
None
> fix: remove debug output

- .dockerignore
- docker/cache/.cache/.gitignore
- docker/cache/.npm/.gitignore
Remove obsolete docker artifacts from version 0.19
- Remove docker npm cache
- Ignore nyc output from docker context
None
None
> build: remove unnecessary docker artifacts

- package-lock.json
- package.json
Bumping version to 0.20.0-dev.5
Bumped version to 0.20.0-dev.5
None
> chore: bump version to 0.20.0-dev.5

- .github/workflows/test_and_release.yml
We were building an unneeded armv7 image
- Remove build for armv7
In CI
None
> ci: don't built for armv7

- .github/workflows/test_and_release.yml
Release was failing with `unauthorized: incorrect username or password`
Try to use previous variable name for release
Untested, will test immediately after merging
None
> ci: use correct dockerhub var names

- .github/workflows/.env
- .github/workflows/test_and_release.yml
- Dockerfile
- package-lock.json
- package.json
We need to update to node 16
- Update package to node 16
- Run tests
- Update Docker base image
- Update CI
In CI
Docker tested locally
None
> chore: update package for node 16
