dashevo/dapi

deploy.sh
* Use "set -x" to show script commands and output, and "-e" to err if anything breaks
* Remove superfluous echo statements (we already know what it's doing now ^)
* Update image name to dashpay/dapi
* Remove ECR related deploy bits, including REPO_URL and repo url in tags
=> Deploy Docker image to Docker Hub

lib/externalApis/dashcore/rpc.js, lib/externalApis/insight/index.js, test/unit/api/dashcore/rpc.js, test/unit/api/insight/insight.js, test/unit/rpcServer/commands/generate.js, test/unit/rpcServer/commands/getBlockHash.js
**Issue being fixed or implemented**
- remove getHashFromHeight from insight and core APIs ( it's never used in dapi-client and it has the same functionality as getBlockHash)
- remove getBlockHash from insight to not support unused code
**What was done**
only getBlockHash from core API remained.
**What has been tested**
test code updated, integration tests were run
**What needs to be tested**
no additional verification required ( unit and integration tests should pass)
=> remove getHashFromHeight & updates for getBlockHash

lib/grpcServer/createServer.js, lib/grpcServer/error/GrpcError.js, lib/grpcServer/error/InternalError.js, lib/grpcServer/error/InvalidArgumentError.js, lib/grpcServer/error/wrapInErrorHandlerFactory.js, test/unit/grpcServer/error/GrpcError.spec.js, test/unit/grpcServer/error/InternalError.spec.js, test/unit/grpcServer/error/InvalidArgumentError.spec.js, test/unit/grpcServer/error/wrapInErrorHandlerFactory.spec.js
In order to handle errors from GRPC method handlers, I wrapped them into additional closure with error handling logic.
=> Handle errors from GRPC method handlers

lib/services/userIndex.js
**Issue being fixed or implemented**
now in userIndex we start with lastProcessedBlock=1. When we launch clean master node and generate genesis block we trigger indexing with lastProcessedBlock += 1; => block out of range
**What was done**
initial lastProcessedBlock=0 and we should start indexing from the first block
**What has been tested**
integration tests works with the fix
*What needs to be tested*
no additional verification required ( unit and integration tests should pass)
=> Start lastProcessedBlock with 0 for userIndex

package.json
- Automatically inserts current version number in swagger template
=> Use `package.json` version when generating OAS

lib/rpcServer/commands/fetchDocuments.js
- Was setting integer default to empty string instead of number
Are these good default values to use? They are really only relevant if importing the spec into a site for hosting interactively.
=> Update `fetchDocuments` OAS default values

scripts/tx-filter-stream.js
Fixes the issue that prevents `npm run tx-filter-stream` from working properly if a `.env` file is used by moving `dotenv.config();` to match how it is done in [`api.js`](https://github.com/dashevo/dapi/blob/v0.10-dev/scripts/api.js#L20-L23).
If possible, it seems like this would be better done in [`lib/config/index.js`](https://github.com/dashevo/dapi/blob/v0.10-dev/lib/config/index.js#L47) and removed from the other locations.
Thanks to @nmarley for helping out.
Fixes #228
=> fix: load .env at correct time for tx-filter-stream

lib/rpcServer/errorHandlerDecorator.js
Updated return error code according to a spec [here](https://www.jsonrpc.org/specification#error_object)
Updated return error code to a `-32603` for internal errors
Tested using running `mn-bootstrap` using custom pre-built `dapi` image. And checking error code returned by the `dapi-client`
Error code for internal errors now `-32603`, as per spec.
=> fix!: invalid JSON RPC internal error code

package-lock.json, package.json, test/functional/grpcServer/handlers/core/getBlockHandlerFactory.spec.js, test/functional/grpcServer/handlers/core/getStatusHandlerFactory.spec.js, test/functional/grpcServer/handlers/core/getTransactionHandlerFactory.spec.js, test/functional/grpcServer/handlers/core/sendTransactionHandlerFactory.spec.js, test/functional/grpcServer/handlers/platform/getDataContractHandlerFactory.spec.js, test/functional/grpcServer/handlers/platform/getDocumentsHandlerFactory.spec.js, test/functional/grpcServer/handlers/platform/getIdentityByFirstPublicKeyHandlerFactory.spec.js, test/functional/grpcServer/handlers/platform/getIdentityHandlerFactory.spec.js, test/functional/grpcServer/handlers/platform/getIdentityIdByFirstPublicKeyHandlerFactory.spec.js, test/functional/grpcServer/handlers/platform/topUpIdentity.spec.js, test/functional/grpcServer/handlers/platform/validateIdentityPublicKeyUniqueness.spec.js, test/functional/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.spec.js, test/functional/rpcServer/commands/getAddressSummary.spec.js, test/functional/rpcServer/commands/getBlockHash.spec.js
Functional tests needed to be updated to work with the new version of DAPI client. 
Old DAPI client methods in functional tests were replaced with the new ones
With functional tests 
DAPI client methods have been changed.
Need to use the new version of js-dp-services-ctl.
=> test: update functional tests to work with dapi-client v0.14

lib/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.js, lib/transactionsFilter/subscribeToNewTransactions.js
Slowdown stream time reduced from 1 second/block to 50milliseconds
Changed stream slowdown from 1 second/matched Merkle block to 50 milliseconds.
Rationale:
Assuming that an active user makes 5 payments a day on average, with 50 milliseconds slowdown the stream will supply the history for 5 years of active everyday usage in about 8 minutes: `5(years) * 365 * 5(payments a day) / (60 / 0.05) ≈ 7.6`, which is a reasonable amount of time.
None
=> feat: reduce artifical slowdown of the transaction stream

lib/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.js, test/unit/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.spec.js
Internal error is thrown when `options.fromBlockHeight` is submitted as `0` to `subscribeToTransactionsWithProofs`
Added assertions for `fromBlockHeight` value to be more then `0`
Unit tests.
None.
=> fix: internal error when `fromBlockHeight` submitted as 0  to `subscribeToTransactionsWithProofs`

lib/grpcServer/handlers/core/broadcastTransactionHandlerFactory.js, lib/grpcServer/handlers/core/coreHandlersFactory.js, lib/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js, lib/grpcServer/handlers/platform/platformHandlersFactory.js, package-lock.json, package.json, test/unit/grpcServer/handlers/core/broadcastTransactionHandlerFactory.js, test/unit/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js
In order to more accurately name DAPI and DAPI gRPC endpoints we need to rename sendTransaction and applyStateTransition methods.
sendTransaction renamed to broadcastTransaction
applyStateTransition renamed to broadcastStateTransition
dapi-grpc updated to 0.15.0-dev.1
Unit tests
sendTransaction renamed to broadcastTransaction
applyStateTransition renamed to broadcastStateTransition
=> feat!: rename sendTransaction and applyStateTransition to broadcast

lib/grpcServer/handlers/platform/platformHandlersFactory.js
Due to the wrong import names, `broadcastStateTransition` method was broken.
Replaced variable names with the right ones.
Tests
None
=> fix: bad import namings in platform handlers

.env.example, lib/grpcServer/handlers/core/coreHandlersFactory.js, lib/grpcServer/handlers/platform/platformHandlersFactory.js, package-lock.json, package.json, scripts/api.js, scripts/tx-filter-stream.js
We need better error reporting to make the debugging process easier
Debug mode was added to respond internal error with message and stack
grpc-common updated to 0.3.1
Unit tests
No
=> feat: debug mode to respond internal error with message and stack

lib/externalApis/drive/DriveStateRepository.js, test/unit/api/drive/DriveStateRepository.js
Replace drive endpoints with new ones
Tests
=> feat: use Drive 0.16 endpoints

lib/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.js
`count too big` error during the js client sync due to the fact that the client doesn't know the exact height becasue header chain sync is currently not supported via DAPI. Needs to be reverted back once header stream implemented
replaced the code that throws an error with a code that caps block.height+count to the best block height 
None
=> fix: 'count too big' error

lib/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.js
=> fix: instant lock messages not being set properly

lib/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js, test/unit/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js
If state transaction was broadcasted twice, we get Internal error
Fixed broadcastStateTransitionHandler to throw correct error
No
=> feat: throw GrpcError if state transaction was broadcasted twice

lib/grpcServer/handlers/core/getStatusHandlerFactory.js
Time offset from Insight is `-1` but unsign integer is expected
Removed time offset field from getStatus response
The time offset is nil always. 
=> fix(core)!: timeOffset on `getStatus` expected to be uint32

.travis.yml, lib/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js, test/unit/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js
`broadcast_tx_commit` should be used only for debug and development purposes.
Replaced `broadcast_tx_commit` with `broadcast_tx_async`
Tests
No
=> feat: replace `broadcast_tx_commit` with `broadcast_tx_async`

lib/grpcServer/handlers/platform/broadcastStateTransitionHandlerFactory.js
Fixed destructuring of broadcast_tx_sync response
Moved destructuring of broadcast_tx_sync response one level above
Run the tests
None
=> fix: cannot destructure property 'error' of 'result' as it is undefined

lib/errors/DashCoreRpcError.js, lib/externalApis/dashcore/rpc.js, lib/grpcServer/handlers/core/broadcastTransactionHandlerFactory.js, lib/grpcServer/handlers/core/coreHandlersFactory.js, scripts/api.js, test/unit/grpcServer/handlers/core/broadcastTransactionHandlerFactory.js
This PR brings support for broadcastTransaction without insight
- feat: provide broadcastTransaction using core RPC instead of insight
Using test suite
N/A
=> feat: provide broadcastTransaction without insight

lib/externalApis/dashcore/rpc.js, lib/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.js, lib/transactionsFilter/ProcessMediator.js, lib/transactionsFilter/getMemPoolTransactionsFactory.js, lib/transactionsFilter/subscribeToNewTransactions.js, lib/transactionsFilter/testRawTransactionAgainstFilterCollectionFactory.js, scripts/tx-filter-stream.js, test/integration/transactionsFilter/subscribeToNewTransactions.spec.js, test/unit/grpcServer/handlers/tx-filter-stream/subscribeToTransactionsWithProofsHandlerFactory.spec.js
If the client was reconnected to `subscribeToTransactionsWithProofs` or it was connected after transaction was emitted, there will be no instantLock event emitted.
Scan mempool for new transactions
No
=> fix: `subscribeToTransactionsWithProofsHandler` misses transactions from mempool

.github/workflows/.env, lib/dpp/DriveStateRepository.js, lib/externalApis/drive/DriveClient.js, lib/externalApis/drive/fetchProofForStateTransitionFactory.js, lib/grpcServer/handlers/platform/getDataContractHandlerFactory.js, lib/grpcServer/handlers/platform/getDocumentsHandlerFactory.js, lib/grpcServer/handlers/platform/getIdentitiesByPublicKeyHashesHandlerFactory.js, lib/grpcServer/handlers/platform/getIdentityHandlerFactory.js, lib/grpcServer/handlers/platform/getIdentityIdsByPublicKeyHashesHandlerFactory.js, lib/grpcServer/handlers/platform/waitForStateTransitionResultHandlerFactory.js, package-lock.json, package.json, test/integration/dpp/DriveStateRepository.spec.js, test/integration/grpcServer/handlers/platform/waitForStateTransitionResultHandlerFactory.js, test/unit/externalApis/drive/DriveClient.js, test/unit/grpcServer/handlers/platform/getDataContractHandlerFactory.js, test/unit/grpcServer/handlers/platform/getDocumentsHandlerFactory.js, test/unit/grpcServer/handlers/platform/getIdentitiesByPublicKeyHashesHandlerFactory.js, test/unit/grpcServer/handlers/platform/getIdentityHandlerFactory.js, test/unit/grpcServer/handlers/platform/getIdentityIdsByPublicKeyHashesHandlerFactory.js
To provide metadata and more information with proofs for platform endpoints. Since proofs include data already it shouldn't be sent in case of proof is requested. https://github.com/dashevo/js-drive/pull/518
- updated `dapi-grpc`
- updated Drive client to handle both Protobuf and CBOR responses
- updated query handlers
Unit tests
Data is nil in case if a proof is requested from platform endpoints
=> feat!: add more information to proofs

lib/externalApis/tenderdash/WsClient.js
Due to the nature of `Docker` a DNS error may occur on an early start of `DAPI` container leading to `EAI_AGAIN` error
- `EAI_AGAIN` error code being handled with `reconnect` logic
Local setup
None.
=> fix: EAI_AGAIN error code was not handled in a client

.github/workflows/test_and_release.yml
Release builds were not hitting cache
- Use same cache key for release build
In CI
None
=> ci: cache miss on release job

lib/externalApis/drive/DriveClient.js, test/unit/externalApis/drive/DriveClient.js
`prove` options was sent to `Tenderdash` as a `string` rather than `boolean`
- changed the type
Local setup
None.
=> fix: `prove` options was set as a string
